### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by Dazani5** [rbtl-fs24/md-02-assignments-Dazani5#1]
@larnsce

Sometimes, the qmd file mixed up "continent" and "country", is this possible?

**Comment by larnsce** [comment]
Thank you for completing the assignment, @Dazani5. I have had a look at your code and it looks great. Well done. 👏🏼

Yes, that might be a typo from my side. Could you share a permalink from the line in the script where you discovered that? You can do that by:

1. Opening the .qmd file on GitHub: https://github.com/rbtl-fs24/md-02-assignments-Dazani5/blob/main/md-02a-data-visualization.qmd
2. Scrolling to the line number where you discovered it.
3. Click on line number (highlights yellow), then click on three small dots on the left.
4. Select "Copy permalink"

The result: https://github.com/rbtl-fs24/md-02-assignments-Dazani5/blob/679606ddf4c18cb8a400c2370944d38404dc1266/md-02a-data-visualization.qmd#L30

**Comment by Dazani5** [comment]
Sure:

1. https://github.com/rbtl-fs24/md-02-assignments-Dazani5/blob/679606ddf4c18cb8a400c2370944d38404dc1266/md-02a-data-visualization.qmd#L140 --> I am not sure about this one, but the instructions are to map continent to both the x-axis and the fill color, which seemed strange to me, since the color in this case does not add any new information to the plot. Should it have been colored by country?

2. https://github.com/rbtl-fs24/md-02-assignments-Dazani5/blob/679606ddf4c18cb8a400c2370944d38404dc1266/md-02a-data-visualization.qmd#L251 --> here am I more sure, since the line asks us to map "**country** to color using the `color = **continent**` argument inside `aes()`", which seems a contradiction.

Thanks!

**Comment by larnsce** [comment]
Thanks a lot, @Dazani5. You have just helped me improve the assignment:

https://github.com/rbtl-dev/md-02-assignments/commit/d67a7e5e997344354ccc1fc25528c9933cbe868f

> --> I am not sure about this one, but the instructions are to map continent to both the x-axis and the fill color, which seemed strange to me, since the color in this case does not add any new information to the plot. Should it have been colored by country?

You are right, it does not add any additional information. That's a great observation. This technique is sometimes used in combination with removing the legend. It adds color to the plot, which can make it visually more appealing. But, with the legend, there isn't much added value.
